### ISSUE TITLE
Use Postgresql as local db

### ISSUE THREAD

**Issue by knwang** [gotealeaf/Interview-Questions#9]
should be pretty simple.. but use postgres as local db so we can run the heroku db dump script (I added as part of the last merge) and pull down production data to local.

**Comment by tomtomecek** [comment]
I had to change the shell script - heroku pg backups is deprecated and newer version requires different syntax. Read more [here](https://devcenter.heroku.com/articles/mapping-pgbackups-commands#downloading-your-backup).

**Comment by knwang** [comment]
merged. looks good @tomtomecek
